_wandb:
    value:
        cli_version: 0.25.1
        e:
            b7pi3xdd701f9x2ixbup68r3rx8afes7:
                args:
                    - --episodes
                    - "600"
                    - --lr
                    - "1e-4"
                    - --batch-size
                    - "64"
                    - --buffer-size
                    - "10000"
                    - --gamma
                    - "0.99"
                    - --eps-start
                    - "1.0"
                    - --eps-end
                    - "0.01"
                    - --eps-decay
                    - "500"
                    - --target-update
                    - "3"
                    - --warmup
                    - "1000"
                    - --eval-interval
                    - "20"
                    - --eval-episodes
                    - "10"
                    - --wandb-project
                    - DQN-CartPole
                codePath: dqn/dqn.py
                codePathLocal: dqn/dqn.py
                cpu_count: 20
                cpu_count_logical: 40
                cudaVersion: "12.5"
                disk:
                    /:
                        total: "32145145856"
                        used: "28265168896"
                email: jan.matthias@hotmail.com
                executable: /users/jmatthia/deep_learning/env/bin/python
                gpu: Tesla V100S-PCIE-32GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "34359738368"
                      name: Tesla V100S-PCIE-32GB
                      uuid: GPU-89a7d5e4-217c-06c9-67f7-04af445dccf6
                host: compute-123.cm.cluster
                memory:
                    total: "810214969344"
                os: Linux-5.14.0-427.13.1.el9_4.x86_64-x86_64-with-glibc2.34
                program: /users/jmatthia/deep_learning/code/assignment_6/dqn/dqn.py
                python: CPython 3.10.20
                root: /users/jmatthia/deep_learning/code/assignment_6
                slurm:
                    cluster_name: jhpce3
                    conf: /etc/slurm/slurm.conf
                    cpus_on_node: "4"
                    cpus_per_task: "4"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: jhpce
                    job_cpus_per_node: "4"
                    job_gid: "100"
                    job_gpus: "0"
                    job_id: "30767493"
                    job_name: dqn_cartpole
                    job_nodelist: compute-123
                    job_num_nodes: "1"
                    job_partition: gpu
                    job_qos: normal
                    job_uid: "57545"
                    job_user: jmatthia
                    jobid: "30767493"
                    localid: "0"
                    mem_per_node: "16384"
                    nnodes: "1"
                    node_aliases: (null)
                    nodeid: "0"
                    nodelist: compute-123
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    submit_dir: /users/jmatthia/deep_learning/code/assignment_6
                    submit_host: jhpce01.cm.cluster
                    task_pid: "294094"
                    tasks_per_node: "1"
                    topology_addr: compute-123
                    topology_addr_pattern: node
                    working_cluster: jhpce3:usher05:6817:9728:109
                startedAt: "2026-04-12T16:31:19.767208Z"
                writerId: b7pi3xdd701f9x2ixbup68r3rx8afes7
        m: []
        python_version: 3.10.20
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.20
            "5": 0.25.1
            "12": 0.25.1
            "13": linux-x86_64
batch_size:
    value: 64
buffer_size:
    value: 10000
episodes:
    value: 600
eps_decay:
    value: 500
eps_end:
    value: 0.01
eps_start:
    value: 1
eval_episodes:
    value: 10
eval_interval:
    value: 20
gamma:
    value: 0.99
lr:
    value: 0.0001
target_update:
    value: 3
wandb_project:
    value: DQN-CartPole
warmup:
    value: 1000
