_wandb:
    value:
        cli_version: 0.25.1
        e:
            dfmmm3a14yitqgvar32aqev9ohw6hyrb:
                args:
                    - --epochs
                    - "70"
                    - --batch-size
                    - "64"
                    - --lr
                    - "2e-4"
                    - --data-root
                    - /users/jmatthia/deep_learning/data
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 24
                cpu_count_logical: 48
                cudaVersion: "12.5"
                disk:
                    /:
                        total: "32145145856"
                        used: "27945627648"
                email: jan.matthias@hotmail.com
                executable: /users/jmatthia/deep_learning/env/bin/python
                gpu: NVIDIA A100 80GB PCIe
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100 80GB PCIe
                      uuid: GPU-c127205e-3218-777b-3add-8288dcf3de28
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100 80GB PCIe
                      uuid: GPU-8f21f64d-dfec-41ad-d847-f03a351fbdd0
                host: compute-128.cm.cluster
                memory:
                    total: "540334850048"
                os: Linux-5.14.0-427.13.1.el9_4.x86_64-x86_64-with-glibc2.34
                program: /users/jmatthia/deep_learning/code/assignment_5/train.py
                python: CPython 3.10.20
                root: /users/jmatthia/deep_learning/code/assignment_5
                slurm:
                    cluster_name: jhpce3
                    conf: /etc/slurm/slurm.conf
                    cpus_on_node: "4"
                    cpus_per_task: "4"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: jhpce
                    job_cpus_per_node: "4"
                    job_gid: "100"
                    job_gpus: "2"
                    job_id: "30605943"
                    job_name: swin_b_cifar100
                    job_nodelist: compute-128
                    job_num_nodes: "1"
                    job_partition: gpu
                    job_qos: normal
                    job_uid: "57545"
                    job_user: jmatthia
                    jobid: "30605943"
                    localid: "0"
                    mem_per_node: "49152"
                    nnodes: "1"
                    node_aliases: (null)
                    nodeid: "0"
                    nodelist: compute-128
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    submit_dir: /users/jmatthia/deep_learning/code/assignment_5
                    submit_host: jhpce01.cm.cluster
                    task_pid: "681880"
                    tasks_per_node: "1"
                    topology_addr: compute-128
                    topology_addr_pattern: node
                    working_cluster: jhpce3:usher05:6817:9728:109
                startedAt: "2026-04-06T03:28:10.410291Z"
                writerId: dfmmm3a14yitqgvar32aqev9ohw6hyrb
        m: []
        python_version: 3.10.20
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 16
            "4": 3.10.20
            "5": 0.25.1
            "12": 0.25.1
            "13": linux-x86_64
batch_size:
    value: 64
learning_rate:
    value: 0.0002
model_type:
    value: swin_b
n_classes:
    value: 100
n_epochs:
    value: 70
patience:
    value: 10
weight_decay:
    value: 0.05
